import './globals.css'
import { Inter } from 'next/font/google'

import {ClientProvider} from '../Redux/Provider'
const inter = Inter({ subsets: ['latin'] })
import ProgresBar from '@/components/Progresbar/ProgresBar'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClientProvider>
        <ProgresBar>
      <body className={inter.className}>{children}</body>
     </ProgresBar>
      </ClientProvider>
    </html>
  )
}
